import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]

[window]
dynamic_padding = true

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size= 10
offset= { x = 0, y = -1}